### ISSUE TITLE
Not connected to Teamspeak

### ISSUE THREAD

**Issue by Badetuch** [kallefrombosnia/TS3-Web-channel-menager#1]
Hello, when i open the Page it says "Aww snap. You need to connect on our TS3 server to use this feature."
But im connected and also pressed the "Connect" Button and refreshed. Even the Query bot connects: http://prntscr.com/lpnh7v.

Here is my Config.php: https://hastebin.com/ojegoxaquw

hope u can help me :)

**Comment by kallefrombosnia** [comment]
Hi, thanks for using this project.
To debug this, do you use TS3 Hook to hide ip or something like that? 

Also your paste has expired.

**Comment by Badetuch** [comment]
Hey, here is my config: Deleted

No i don´t use anything like Tshook.

**Comment by kallefrombosnia** [comment]
> Hey, here is my config: Deleted
> 
> No i don´t use anything like Tshook.

Sorry but I cant replicate error that you are facing, so I am closing this issue right now.
Also edited your comment because of personal info.
